### ISSUE TITLE
expose the mail attribute in the config class

### ISSUE THREAD

**Issue by chupman** [theforeman/ldap_fluff#39]
I was hoping to add the option of enabling login support via the mail field in addition to the login_attr field. To do this without hard coding the attribute the config class would need to also expose the mail field from the foreman ldap configuration.

Use Case:
If a directory service uses serial numbers for employee uid and groupOfUniqueNames mappings, but users use an email for logins I believe it is current impossible to configure ldap with both group support and the ability to login with the user preferred attribute.

I think a conditional could be added to the  member_service.find_user method to translate the email address supplied by the user to their login_attr if an @ is contained in the uid string.

**Comment by eLobato** [comment]
@chupman That sounds reasonable, I've opened a [ticket for it in the Foreman tracker](http://projects.theforeman.org/issues/9499) as I think what you propose is feasible without changes to ldap_fluff, just to Foreman (support several login_attr fields). Thanks much!

(I just stumbled upon the issue now, really sorry for that)
