### ISSUE TITLE
Users with commas in their CNs cause errors

### ISSUE THREAD

**Issue by jaredjennings** [theforeman/ldap_fluff#45]
My DN is `cn=Jennings\, Jared,ou=Foo,ou=Bar,ou=Baz,dc=example,dc=org`. That is, my common name is `Jennings, Jared`. I'm in an Active Directory. ldap_fluff 0.3.2-1.el7 can't tell that I exist, and throws an error if you ask it for a user list of any group I'm in.

It appears that the root cause is that `LdapFluff::GenericMemberService#find_by_dn` splits the DN on commas, takes the first comma-delimited piece, and assumes it's the whole CN (or uid, or some attribute). So `entry` ends up being `cn=Jennings\`, and `base` ends up being ` Jared,ou=Foo,ou=Bar,ou=Baz,dc=example,dc=org`. That value for `base` is not a syntactically valid DN, besides there being no users with CN `Jennings\`.

**Comment by jaredjennings** [comment]
I have a failing test and a fix, and perhaps this is one of those things where a simple pull request might do, but I'm behind a firewall I haven't used GitHub from before, so I'll just file this and then worry about getting the patches out.

**Comment by domcleal** [comment]
See also #38, which is incomplete.

**Comment by jaredjennings** [comment]
Having figured out the firewall issues, and taking some important cues from #38 (thanks, @brgerig) I've filed PR #46 to see if it will ... travis properly. GitHub appears to have unified pull requests and issues more than I remember, so I'm closing this issue and referring further discussion to #46.
