### ISSUE TITLE
Use `msds-memberoftransitive` for AD group lookups

### ISSUE THREAD

**Issue by 0x6d617474** [theforeman/ldap_fluff#68]
The [msds-memberOfTransitive](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adls/dcddfdd8-5c70-45b7-bc64-a714ed2ca621) attribute was added in Windows Server 2012 R2, which provides a much more efficient way to get the full list of group memberships without needing to do recursive lookups. 

The attribute requires the search base be set to the DN of the object you are querying, but will compute the full list of groups on the domain controller, which saves a lot of client-side work and subsequent connections. 

It would be great if the library attempted this method of group membership lookup first, and then failing that it would revert to the recursive lookup method. For any 2012 R2 server and up, this should result in much faster lookup times.

**Comment by ezr-ondrej** [comment]
Sounds good, I can try to do something about it, but I'm not sure how to manage the fallback.

**Comment by 0x6d617474** [comment]
I imagine that the LDAP call to AD will fail with an error if the requested attribute does not exist, but sadly I don't have an AD instance that doesn't have the attribute to test with to be sure.
